# Generated by Django 3.2.5 on 2021-07-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=100, verbose_name='Index')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('mail', models.TextField(verbose_name='E-mail')),
                ('registration_date', models.CharField(max_length=50, verbose_name='Reg. date')),
                ('status', models.TextField(verbose_name='Status')),
            ],
        ),
    ]
